### ISSUE TITLE
[signIn_signUp] create mockup of sign-in pages

### ISSUE THREAD

**Issue by thengthon** [pnc-virtual-company/2021-G8-VC2-PART2#1]
We design mockups for sign-in pages.

There are two pages for sign-in process.

**Comment by Lyheang187** [comment]
<img width="2854" alt="Login page" src="https://user-images.githubusercontent.com/77564844/146853719-009f35b7-20e9-4363-8b16-ffbf3fe21e04.png">

@ronanpnc
