### ISSUE TITLE
[development] sprint review - iteration 1

### ISSUE THREAD

**Issue by thengthon** [pnc-virtual-company/2021-G8-VC2-PART2#23]
- Invite people button must be at Manage user page.
- Send mail to people when ERO invited them.
- Change margin in text fields.
- Don't show the features to the costumer that haven't done.
- Add phone number when user login in first time.
- Change color main page and login page to similar. 
- Features in explore alumni page are too much (keep them in one).
- Change color and size of log out button.
- Do the edit and create in profile page (plan next week)
- Think of major and batch (when fill?)
- Add skills into profile page.
- change color icon to one color.
- add background in main page. (like login page)
- change size app bar to bigger.
- Invite the many people in one time. 
- Can we edit company ?

**Comment by ronanpnc** [comment]
Sreyngit-Doeurm Worklog Template(260).xlsx
Dear respected tutor @Sreypichly please check my worklog. Thank you teacher

**Comment by sreyngitdoeurm** [comment]
[Sreyngit-Doeurm Worklog Template(260).xlsx](https://github.com/pnc-virtual-company/2021-G8-VC2-PART2/files/7767035/Sreyngit-Doeurm.Worklog.Template.260.xlsx)
Dear, respected tutor @Sreypichly , I hope you're doing well. This is my worklog for iteration 1. Thank you teacher

**Comment by Lyhuoy** [comment]
https://docs.google.com/spreadsheets/d/1u9KQWW6kt3F_lgNwsVOmEE7E5CXssZNZ/edit#gid=660838242
Dear, respected tutor @Sreypichly  ,I hope you're doing well. This is my worklog for iteration 1. Thank you for your pay attention.

**Comment by Lyhuoy** [comment]
https://docs.google.com/spreadsheets/d/1u9KQWW6kt3F_lgNwsVOmEE7E5CXssZNZ/edit?usp=sharing&ouid=103066655328087272403&rtpof=true&sd=true
Dear, respected tutor @Sreypichly , I hope you're doing well. This is my worklog for iteration 1. Thank you for your pay attention.

**Comment by thengthon** [comment]
[Thon_THENG_Weekly_Worklog.xlsx](https://github.com/pnc-virtual-company/2021-G8-VC2-PART2/files/7767539/Thon_THENG_Weekly_Worklog.xlsx)


Dear Mss. @Sreypichly 

Good afternoon teacher, I hope you are doing great.
I would like to submit my worklog for the first week here.

Thank you.
Thon THENG

**Comment by SENKUNTHY** [comment]
Dear Miss. @Sreypichly 
Good morning tutor, I really hope that you are fine.
I would like to send you my worklog for the first week of my project here.
[KunthySEN-Worklog-VC2-Part2.xlsx](https://github.com/pnc-virtual-company/2021-G8-VC2-PART2/files/7772407/KunthySEN-Worklog-VC2-Part2.xlsx)

Thanks
Kunthy SEN

**Comment by Lyheang187** [comment]
Dear Miss. @Sreypichly
Good morning tutor, I really hope that you are fine.
I would like to send you my worklog for the first week of my project here.
[Worklog Template Lyheang Chhem.xlsx](https://github.com/pnc-virtual-company/2021-G8-VC2-PART2/files/7772485/Worklog.Template.Lyheang.Chhem.xlsx)
Thanks
Lyheang Chhem

**Comment by lyhuoy** [comment]
[Worklog Template.xlsx](https://github.com/pnc-virtual-company/2021-G8-VC2-PART2/files/7773419/Worklog.Template.xlsx)

Dear, respected tutor @Sreypichly , I hope you're doing well. This is my worklog for iteration 1. Thank you for your pay attention.
