### ISSUE TITLE
Sprint planning for iteration 2

### ISSUE THREAD

**Issue by Lyheang187** [pnc-virtual-company/2021-G8-VC2-PART2#37]
I am writing this message to send you about our planning for iteration 2. I want you to check our planning.
Here are what we will do:

1. Complete the task in alumni profile page:
- Display real data of alumni info
- Edit alumni info
- Upload image profile
- Add the current employment.
2. On explore alumni page:
- Change button invite people to Manage user page
- ERO also can use the Manage user page
3. On Manage user page:
- Invite with many people in one time
- Change role of viewing user table:
* ERO can delete alumni
* Admin can delete both (ERO and alumni)
4. Improve UI:
- Change color icon
- Change size of app bar to bigger
- Chane button style.

**Comment by Lyheang187** [comment]
Dear Valued Customer,
Good afternoon @Sethmok , I really hope that you are fine.
I'm writing this to inform you that we have planed about what we will do in iteration2. 
If you want to add something more please take a look on the description above.

Thanks for you time, if you have any concern please contact us back.

Best regards,
Lyheang CHHEM

**Comment by Sethmok** [comment]
Thanks @Lyheang187 very good. Don't forget to send me mock up of all page if you have, so I can validate.
