### ISSUE TITLE
[signIn_signUp] manage user on backend

### ISSUE THREAD

**Issue by thengthon** [pnc-virtual-company/2021-G8-VC2-PART2#5]
We manage users when we register or log in on the backend.

**Comment by SENKUNTHY** [comment]
If you want to check database please look at relationship below:
<img width="527" alt="alumniDB" src="https://user-images.githubusercontent.com/77561655/146665009-00269440-2fad-4e9d-8891-9d02b2237433.PNG">
I followed it.
