### ISSUE TITLE
Discuss Sprint Review 2 and Planning next iteration

### ISSUE THREAD

**Issue by SENKUNTHY** [pnc-virtual-company/2021-G8-VC2-PART2#59]
Dear @ronanpnc , @Sreypichly , @Sethmok 
I really hope that you all well. I would like to sharing you about the planning with the iteration 3.

ON SIGN IN:
-	Manage forget password when users forget
-	Create link to contact the ERO for validate email of alumni when alumni forget their email
ON ALUMNI : 
-	[PROFILE] Remove color after three dots just only icon edit and delete is enough
-	[PROFILE] Edit Company information
-	[PROFILE] Update skill when create not to duplicate
-	[PROFILE] Should have icon to remove skill when alumni confused when create 
-	[PROFILE] Validate start date should before end date on employment work
ON ERO OFFICER: 
-	[EXPLORER ALUMNI] Search alumni using filters
-	Increase margin from each card
ON ERO ADMIN: 
-	[MANAGE USER] Invite many alumni and ERO just copy email and convert to small chips auto and email 
-	[MANAGE USER] Mange email auto when admin or ERO have been invite to alumni and ERO (IF WE CAN)
 ON EVENT (EXTRA):
-	Manage event

=>For the feedbacks and information for our team work please kindly take a look on file below
[GROUP8 - SPRINT REVIEW2.docx](https://github.com/pnc-virtual-company/2021-G8-VC2-PART2/files/7795240/GROUP8.-.SPRINT.REVIEW2.docx)

=> Team members:
@SENKUNTHY 
@Lyheang187 
@thengthon 
@sreyngitdoeurm 
@Lyhuoy 

Best Regard,
Kunthy SEN

**Comment by ronanpnc** [comment]
Hello @SENKUNTHY 

	SIGN IN : Should have the link to contact to ERO to validate email when alumni forget their email

==> it ould be nice inteastead to  :  send a email to the alumni for  password reset  (like usual apps)

**Comment by SENKUNTHY** [comment]
Hello @ronanpnc 
Now we are fixing some bugs and try to finish on skill , search filter on Explore Alumni and Manage User 
For SIGN IN we will do it that we need to have a link to contact ERO to validate email when alumni forget their email but maybe later because we need to fix something more. If you have any feedbacks more please let us know.

THANKS
