### ISSUE TITLE
[alumni] Validate date on employment work

### ISSUE THREAD

**Issue by SENKUNTHY** [pnc-virtual-company/2021-G8-VC2-PART2#60]
=> Validate date for employment work start date must be before end date
=> manage date format

**Comment by thengthon** [comment]
@ronanpnc 

https://github.com/pnc-virtual-company/2021-G8-VC2-PART2/commit/b6b88e3a6777377047b37239b794941ff6549f98

This is the code that I pushed on this issue, I am sorry because I forgot to link with the issue.
